# Generated by Django 5.1.1 on 2024-09-17 12:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CharacteristicGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256, verbose_name='Название группы')),
            ],
            options={
                'verbose_name': 'Группа характеристики',
                'verbose_name_plural': 'Группы характеристики',
            },
        ),
        migrations.CreateModel(
            name='Characteristic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=256, verbose_name='Название характеристики')),
                ('value', models.CharField(max_length=1024, verbose_name='Значение')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristics', to='products.characteristicgroup', verbose_name='Группа характеристик')),
            ],
            options={
                'verbose_name': 'Характеристика',
                'verbose_name_plural': 'Характеристики',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('uuid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID')),
                ('slug', models.SlugField(blank=True, max_length=256, unique=True, verbose_name='Slug')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('product_image', models.ImageField(blank=True, null=True, upload_to='products/', verbose_name='Изображение')),
                ('specs', models.TextField(max_length=150, verbose_name='Тех. Характеристики')),
                ('description', models.TextField(max_length=1500, verbose_name='Описание')),
                ('sku', models.PositiveBigIntegerField(unique=True, verbose_name='Артикул')),
                ('price', models.DecimalField(decimal_places=2, max_digits=7, verbose_name='Цена')),
                ('price_currency', models.CharField(choices=[('RUB', 'RUB'), ('US', 'US'), ('YEN', 'YEN'), ('EURO', 'EURO'), ('YUAN', 'YUAN')], default='RUB', max_length=4, verbose_name='Валюта')),
                ('stock_quantity', models.PositiveIntegerField(verbose_name='Кол-во на складе')),
                ('is_available', models.BooleanField(verbose_name='В наличии?')),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='main.brand', verbose_name='Бренд')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.AddField(
            model_name='characteristicgroup',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='characteristic_groups', to='products.product', verbose_name='Продукт'),
        ),
    ]
