# Generated by Django 5.1.1 on 2024-09-24 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='periods',
            field=models.CharField(choices=[('Менее месяца', 'Менее месяца'), ('Не более года', 'Не более года'), ('Более года', 'Более года')], max_length=16, verbose_name='Срок использования'),
        ),
    ]
