# Generated by Django 5.1.1 on 2024-09-25 13:00

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('opinion', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='uuid',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='UUID'),
        ),
    ]
