# Generated by Django 5.1.1 on 2024-09-18 13:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0001_initial'),
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='productsubtype',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='products',
            field=models.ManyToManyField(to='products.product', verbose_name='Товары'),
        ),
        migrations.AddField(
            model_name='productsubtype',
            name='product_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_subtypes', to='catalog.producttype', verbose_name='Тип продукта'),
        ),
        migrations.AddField(
            model_name='producttype',
            name='product_variety',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product_types', to='catalog.productvariety', verbose_name='Разновидность продукта'),
        ),
        migrations.AddField(
            model_name='subcategory',
            name='main_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subcategories', to='catalog.maincategory', verbose_name='Главная категория'),
        ),
        migrations.AddField(
            model_name='productvariety',
            name='sub_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_varietys', to='catalog.subcategory', verbose_name='Подкатегория'),
        ),
    ]
